# -*- coding: utf-8 -*-
"""DataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nG03nSxJcussrrgNPtkuqOOUGIQGJmwe
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

data = pd.read_csv("/content/drive/My Drive/CloudProject/dataset/sampleData.csv")
print(data.dtypes)

data = data.drop(['DIVERTED','CANCELLED','AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY', 'WEATHER_DELAY', 'CANCELLATION_REASON', 'LATE_AIRCRAFT_DELAY'], axis=1)

data

#correlation map
f,ax = plt.subplots(figsize=(12, 12))
sns.heatmap(data.corr(), annot=True, linewidths=.5, fmt= '.1f',ax=ax)
plt.show()

plt.savefig('heatmap.JPG')

# extracting numeric data values

# features = [f[0] for f in data.dtypes if f[1] == 'int64' or f[1] == 'float64']

features = data.select_dtypes([np.number]).columns
print(features)

numeric_data = data[['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'FLIGHT_NUMBER',
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'ARRIVAL_DELAY']]

from pandas.plotting import scatter_matrix

axs = scatter_matrix(numeric_data, figsize=(12, 12));
n = len(numeric_data.columns)
for i in range(n):
    v = axs[i, 0]
    v.yaxis.label.set_rotation(0)
    v.yaxis.label.set_ha('right')
    v.set_yticks(())
    h = axs[n-1, i]
    h.xaxis.label.set_rotation(90)
    h.set_xticks(())

