# -*- coding: utf-8 -*-
"""PlotResults.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhLYxXrFl_mpi6vjlFUyj5gKNvgBLQFz
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import roc_auc_score

text_file= open("/content/drive/My Drive/CloudProject/dataset/true_pred.txt",'r')
data=text_file.read()
listOfSentences = data.split("\n")

y_pred = []
y_true = []
for i in listOfSentences:
    if i:
        y_true.append(eval(i)[1][0])
        y_pred.append(eval(i)[1][1])

plt.figure(figsize=(16,8))
plt.plot(np.asarray(y_true))
plt.plot(np.asarray(y_pred))
plt.legend(['y_true', 'y_pred'], loc=1)
plt.show()

fp, tp, thresholds = metrics.roc_curve(np.asarray(y_pred),np.asarray(y_true), pos_label=None)
plt.figure(figsize=(8,6))
plt.plot(fp, tp,linewidth=2, label= None)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.xlim(0,1)
plt.ylim(0,1)
plt.show()

text_file= open("/content/drive/My Drive/CloudProject/dataset/true_pred100k.txt",'r')
data=text_file.read()
listOfSentences = data.split("\n")

y_pred = []
y_true = []
for i in listOfSentences:
    if i:
        y_true.append(eval(i)[1][0])
        y_pred.append(eval(i)[1][1])

plt.figure(figsize=(16,8))
plt.plot(np.asarray(y_true))
plt.plot(np.asarray(y_pred))
plt.legend(['y_true', 'y_pred'], loc=1)
plt.show()

fp, tp, thresholds = metrics.roc_curve(np.asarray(y_pred),np.asarray(y_true), pos_label=None)
plt.figure(figsize=(8,6))
plt.plot(fp, tp,linewidth=2, label= None)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.xlim(0,1)
plt.ylim(0,1)
plt.show()